name: ci

on: push

jobs:
  build:
    container: pandoc/latex:2.9
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes      
      run: |
        mkdir out
        find . -name "*.md" | pandoc -d "./zmh.def" "$i" -o "out/${i%.*}.html"; done
        find . -name "*.md" | pandoc -d "./zmp.def" "$i" -o "out/${i%.*}.pdf"; done
        find . -name "*.md" | pandoc -d "./zmd.def" "$i" -o "out/${i%.*}.docx"; done
        find . -name "*.md" | pandoc -d "./zme.def" "$i" -o "out/${i%.*}.epub"; done
        echo ---
        find . -name "*.org" | pandoc -d "./zoh.def" "$i" -o "out/${i%.*}.html"; done
        find . -name "*.org" | pandoc -d "./zop.def" "$i" -o "out/${i%.*}.pdf"; done
        find . -name "*.org" | pandoc -d "./zod.def" "$i" -o "out/${i%.*}.docx"; done
        find . -name "*.org" | pandoc -d "./zoe.def" "$i" -o "out/${i%.*}.epub"; done


    - uses: actions/upload-artifact@master
      with:
        name: out
        path: out
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: out
        path: out
    - name: run
      run: |
        git config --local user.email "zettelmuseum@gmail.com"
        git config --local user.name "zettelmuseum"
        git add -A
        git commit -m "Add changes" 
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
