name: ci

on: push

jobs:
  build:
    container: pandoc/core:2.9
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes      
      run: |
        mkdir out
        echo hi >hi.txt
        pandoc --standalone --output=out/hi.html hi.txt
    - uses: actions/upload-artifact@master
      with:
        name: out
        path: out
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: out
        path: out
    - name: run
      run: |
        git config --local user.email "zettelmuseum@gmail.com"
        git config --local user.name "zettelmuseum"
        git add -A
        git commit -m "Add changes" 
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
