name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex:2.9
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        echo hi >hi.txt
        pandoc --standalone --output=hi.pdf hi.txt
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
