name: ci

on: push

jobs:
  build:
    container: pandoc/latex:latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes      
      run: |
        mkdir -p out
        cp *.def out
        cd out
        find . -maxdepth 1 | while read i; do test -f "$i.def" && pandoc -d "$i.def" "$i" || echo ;done
        cd ..

    - uses: actions/upload-artifact@master
      with:
        name: out
        path: out
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: out
    - name: run
      run: |
        mv -f out/* .
        rm -rf ./out
        find . -type f -maxdepth 1 | cut -c3- | sort | grep -v ".def" | while read i; do echo "<a href=\"$i\">$i</a><br /><br />" >> index.html; done
        find . -name "*.html" -maxdepth 1 | while read i; do echo "curl -v https://web.archive.org/save/https://zettelmuseum.github.io/z1gh/${i:2}" ;done >webarchive.sh
        find . -name "*.pdf" -maxdepth 1 | while read i; do echo "curl -v https://web.archive.org/save/https://zettelmuseum.github.io/z1gh/${i:2}" ;done >>webarchive.sh
        git config --local user.email "zettelmuseum@gmail.com"
        git config --local user.name "zettelmuseum"
        git add -A
        git commit -m "Add changes" 
        git gc
        git count-objects -vH >git.txt
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
