name: ci

on: push

jobs:
  build:
    container: pandoc/latex:2.9
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes      
      run: |
        mkdir -p out
        # was: ${i%.x}
        find . -name "*.md" | while read i; do pandoc -d "./def/zmh.def" "$i" -o "out/$i.html" ;done
        find . -name "*.md" | while read i; do pandoc -d "./def/zmp.def" "$i" -o "out/$i.pdf" ;done
        find . -name "*.md" | while read i; do pandoc -d "./def/zmd.def" "$i" -o "out/$i.docx" ;done
        find . -name "*.md" | while read i; do pandoc -d "./def/zme.def" "$i" -o "out/$i.epub" ;done
        echo ---
        find . -name "*.org" | while read i; do pandoc -d "./def/zoh.def" "$i" -o "out/$i.html" ;done
        find . -name "*.org" | while read i; do pandoc -d "./def/zop.def" "$i" -o "out/$i.pdf" ;done
        find . -name "*.org" | while read i; do pandoc -d "./def/zod.def" "$i" -o "out/$i.docx" ;done
        find . -name "*.org" | while read i; do pandoc -d "./def/zoe.def" "$i" -o "out/$i.epub" ;done
        echo ---
        find . -name "*.text" | while read i; do pandoc -d "./def/zsb.def" "$i" -o "out/$i.pdf" ;done
        find . -name "*.text" | while read i; do pandoc -d "./def/zsp.def" "$i" -o "out/$i.pptx" ;done
        find . -name "*.text" | while read i; do pandoc -d "./def/zsh.def" "$i" -o "out/$i.html" ;done
        echo ---
        find . -name "*.csv" | while read i; do pandoc -d "./def/zch.def" "$i" -o "out/$i.html" ;done
        find . -name "*.csv" | while read i; do pandoc -d "./def/zcp.def" "$i" -o "out/$i.pdf" ;done

    - uses: actions/upload-artifact@master
      with:
        name: out
        path: out
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: out
    - name: run
      run: |
        mv -f out/* .
        rm -rf ./out
        find . -type f | cut -c3- | while read i; do echo "<a href=\"$i\">$i</a><br /><br />" >> index.html; done
        git config --local user.email "zettelmuseum@gmail.com"
        git config --local user.name "zettelmuseum"
        git add -A
        git commit -m "Add changes" 
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
